// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8OEWbaOO-q20YF9Fb7akZqyUBy02arfA',
    appId: '1:645964152737:web:42021a6bb361940d0795e0',
    messagingSenderId: '645964152737',
    projectId: 'flutterprueba-3484d',
    authDomain: 'flutterprueba-3484d.firebaseapp.com',
    storageBucket: 'flutterprueba-3484d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTI_kuYWAUxriQWOk-3rN_aUomYwKRlTE',
    appId: '1:645964152737:android:3dfa80220e1446750795e0',
    messagingSenderId: '645964152737',
    projectId: 'flutterprueba-3484d',
    storageBucket: 'flutterprueba-3484d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdAUSHf2A7RArjYR9Kt0Ts-pl5GckhjkQ',
    appId: '1:645964152737:ios:9a4d0c49b47657270795e0',
    messagingSenderId: '645964152737',
    projectId: 'flutterprueba-3484d',
    storageBucket: 'flutterprueba-3484d.firebasestorage.app',
    iosClientId: '645964152737-aofng0rt0kim7jnmnnv2mgag31nnfjq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.carloslangac12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdAUSHf2A7RArjYR9Kt0Ts-pl5GckhjkQ',
    appId: '1:645964152737:ios:9a4d0c49b47657270795e0',
    messagingSenderId: '645964152737',
    projectId: 'flutterprueba-3484d',
    storageBucket: 'flutterprueba-3484d.firebasestorage.app',
    iosClientId: '645964152737-aofng0rt0kim7jnmnnv2mgag31nnfjq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.carloslangac12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8OEWbaOO-q20YF9Fb7akZqyUBy02arfA',
    appId: '1:645964152737:web:b414ea378b64648e0795e0',
    messagingSenderId: '645964152737',
    projectId: 'flutterprueba-3484d',
    authDomain: 'flutterprueba-3484d.firebaseapp.com',
    storageBucket: 'flutterprueba-3484d.firebasestorage.app',
  );
}
